site_name: Pythia
site_url: http://secureosv.news
repo_url: https://github.com/secureosv/pythia
docs_dir: doc

pages:
- Home: index.md
- QuickStart: quick_start.md
- CommandLine: getting_started.md
- ExtendedMarkdown: markdown_format.md
- Syntax: syntax.md
- Lists: lists.md
- MemoryModel: memory.md
- Seastar: seastar.md
- JavaScript: js_backend.md
theme: readthedocs