site_name: Pythia
site_url: http://secureosv.news
repo_url: https://github.com/secureosv/pythia
docs_dir: doc

pages:
- Home: getting_started.md
- Syntax: syntax.md
- MemoryModel: memory.md
- Seastar: seastar.md

theme: readthedocs